# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_publicacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=models.CharField(max_length=5000000, verbose_name='Conteúdo'),
        ),
    ]
